apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: memegenerator-client-deploy
  name: memegenerator-client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memegenerator-client-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: memegenerator-client-deploy
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/labproj13/memegenerator-client:latest
        name: memegenerator-client
        ports:
        - containerPort: 8080
        resources: {}
        envFrom:
        - configMapRef:
            name: memegenerator-client-cmap
status: {}